version: "3"
services:

  rabbitmq-server:
    image: giftwishingacr.azurecr.io/rabbitmq-server
    container_name: rabbitmq-server
    build: ./modules/rabbitmq-server
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf

  sftp-server:
    image: giftwishingacr.azurecr.io/sftp-server
    container_name: sftp-server
    build: ./modules/sftp-server
    volumes:
      - sftp-upload:/home/$SFTP_USER/upload
    environment:
      - SFTP_USER=$SFTP_USER
      - QUEUE_ENDPOINT=$QUEUE_ENDPOINT
      - RABBITMQ_SERVER=$RABBITMQ_SERVER
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
    ports:
      - "22:22"
    depends_on:
      - rabbitmq-server

  products-service:
    image: giftwishingacr.azurecr.io/products-service
    build: ./modules/products
    container_name: products-service
    ports:
        - "80:80"
    environment:
      - PORT=80
      - DATABASE_URL=file:./../sqlite/products.db
      - SFTP_URL=$SFTP_URL
      - SFTP_USERNAME=$SFTP_USER
      - SFTP_PASSWORD=$SFTP_PASSWORD
      - RABBITMQ_SERVER=$RABBITMQ_SERVER
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD

    restart: on-failure #TODO: find a better solution for timing the docker image
    depends_on:
      - sftp-server
      - rabbitmq-server

volumes:
  sftp-upload:
    driver: azure_file
    driver_opts:
      share_name: sftp-upload
#      accountname: $STORAGE_VOLUME_USER
#      accountkey: $STORAGE_VOLUME_PASSWORD
      storage_account_name: giftwishingstorage
      remotepath: home

#  rabbitmq-data:
#    driver: azure_file
#    driver_opts:
#      share_name: rabbitmq-data
#      storage_account_name: giftwishingstorage



#Error: Failed to start container sftp-server, Error response: to create containerd task: failed to create shim task: failed to create container 13469c8568487a853ee9573d9c3d41f23cd813a336d38e9a38e2648b00059109: guest RPC failure: failed to create container: failed to run runc create/exec call for container 13469c8568487a853ee9573d9c3d41f23cd813a336d38e9a38e2648b00059109 with exit status 1: container_linux.go:380: starting container process caused: exec: "foo:pass:1001": executable file not found in $PATH: unknown