version: '3.4'

services:
  user-service-development:
    build:
      context: ./modules/user-service
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./modules/user-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
