version: '3.4'

services:
  user-service-development:
    build:
      context: ./modules/user-service
      target: development
    environment:
      - NODE_ENV=development
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - USER_SERVICE_NEO4J_URL=${USER_SERVICE_NEO4J_URL}
      - USER_SERVICE_NEO4J_USERNAME=${USER_SERVICE_NEO4J_USERNAME}
      - USER_SERVICE_NEO4J_PASSWORD=${USER_SERVICE_NEO4J_PASSWORD}
      - USER_SERVICE_AURA_INSTANCENAME=${USER_SERVICE_AURA_INSTANCENAME}
      - USER_SERVICE_JWT_SECRET=${USER_SERVICE_JWT_SECRET}
      - USER_SERVICE_SIGNUP_URL=${USER_SERVICE_SIGNUP_URL}
      - EMAIL_SERVER_URL_LOCAL=${EMAIL_SERVER_URL_LOCAL}
      - EMAIL_SERVER_URL_PROD=${EMAIL_SERVER_URL_PROD}
      - EMAIL_SERVER_ACCESS_TOKEN=${EMAIL_SERVER_ACCESS_TOKEN}
      - EMAIL_SERVER_SENDER_EMAIL=${EMAIL_SERVER_SENDER_EMAIL}
      - EMAIL_SERVER_SENDER_PASSWORD=${EMAIL_SERVER_SENDER_PASSWORD}
    volumes:
      - ./modules/user-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
