version: "3"

services:
  lb:
    image: haproxy
    ports:
      - "8000:8000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  auth-service:
    image: auth-service
    environment:
      - APPID=4500
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - JWT_SECRET=${JWT_SECRET}

  # example-service:
  #   image: example-service
  #   environment:
  #     - APPID=1111
  # nodeapp2:
  #   image: example-service
  #   environment:
  #     - APPID=2222
  # nodeapp3:
  #   image: example-service
  #   environment:
  #     - APPID=3333
