GET http://localhost:8001/all

###
GET http://localhost:8001/
Content-Type: application/json

{
  "friendsList": ["post-ID-example4"]
}

###
GET http://localhost:8001/post-ID-example3

###
POST http://localhost:8001/
Content-Type: application/json

{
  "userId": "post-ID-example4",
  "products": [
    {
      "name": "post-name-example3",
      "url": "post-url-example3"
    }
  ]
}

###
PATCH http://localhost:8001/post-ID-example4
Content-Type: application/json

{
  "products": [
    {
      "name": "patch-name-example4",
      "url": "patch-url-example4"
    },
    {
      "name": "patch-name-example4",
      "url": "patch-url-example4"
    },
    {
      "name": "patch-name-example4",
      "url": "patch-url-example4"
    }
  ]
}
###
DELETE http://localhost:8001/post-ID-example4